### ISSUE TITLE
How to give folder permissions

### ISSUE THREAD

**Issue by 1Map** [jsreport/jsreport-authorization#1]
I am using jsreport Studio.  I can:

1) Create a user and set 
![image](https://user-images.githubusercontent.com/1152458/132193276-d08f1724-3a5f-4675-bb72-f2871a1d2d3a.png)

2) Quest now is.  For the user created, how do I give permission to a folder?

**Comment by pofider** [comment]
Answered here https://forum.jsreport.net/topic/2109/unable-to-set-permissions-on-folders
